/* https://programmers.co.kr/learn/courses/30/lessons/59412 */

SELECT HOUR(DATETIME) AS HOUR, COUNT(1) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) > 8
  AND HOUR(DATETIME) < 20
GROUP BY HOUR
ORDER BY HOUR
