/* https://programmers.co.kr/learn/courses/30/lessons/59411 */

SELECT I.ANIMAL_ID,
       I.NAME
FROM ANIMAL_INS AS I, ANIMAL_OUTS AS O
WHERE I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY (UNIX_TIMESTAMP(O.DATETIME) - UNIX_TIMESTAMP(I.DATETIME)) DESC
LIMIT 2